print("CADENAS DE CARACTERES EJEMPLOS")
print("REMOVEPREFIX")
a=input("Escriba un texto: ")
print("Recuerde que removeprefix solo borra lo escojido si esta al inicio de la cadena")
b=input("Escriba lo que desea retirar de dicho texto: ")
c=a.removeprefix(b)
print(c)
print("PARTION")
d=input("Escriba un texto: ")
print("Recuerde que partion separa una cadena en tres partes basándose en la primera aparición de una subcadena específica. Este método devuelve una tupla con tres elementos")
e=input("Escriba la sybcadena por la cual se va a dividir el texto: ")
f=d.partition(e)
print(f)
print("SWAPCASE")
g=input("Escriba un texto que quiera invertir las mayusculas y las minusculas: ")
h=g.swapcase()
print(h)
print("Ejercicio de clase para remover una palabra")
s=input("Escriba un texto: ")
t=input("Escriba la parte que desea retirar: ")
u=s.replace(t,"")
print(u)
print("EJERCICIOS PAGINA 40")
print("1.Elabore un programa que dada una letra cuente cuantas ocurrencias de esta letra hay.")
i=input("Escriba un texto: ")
j=input("Escriba la letra que desea contar: ")
k=i.count(j)
print("La letra se repite",k,"veces")
print("2.Elabore un programa que dada una cadena diga si todos los simbolos de la cadena son letras.")
l=input("Escriba un texto: ")
if l.isalpha():
    print("Todos los simbolos de la cadena son letras")
else:
    print("Algunos de los simbolos de la cadena no son letras")
print("3. Elabore un programa que dada una cadena cuente las consonantes en dicha cadena.")
m=input("Escriba un texto: ")
n=m.count("a")
o=m.count("e")
p=m.count("i")
q=m.count("o")
r=m.count("u")
print(f"En el texto hay {n} a, {o} e, {p} i, {q} o, {r} u")
